### ISSUE TITLE
ddns.sh: line 7: syntax error: unexpected "("

### ISSUE THREAD

**Issue by cornjosh** [goomadao/openwrt_cloudflare_ipv6_ddns#1]
Hi,
How are you?
I try to run this script on my OpenWrt router, but it doesn't work. The error as it was:
> root@OpenWrt-center:/tmp/upload# sh ddns.sh 
> : not foundne 2: 
> ddns.sh: line 7: syntax error: unexpected "("

I have no idea to solve it. How can I do to make it work?
thanks.

**Comment by cornjosh** [comment]
Hi,
I found the reason for this question. 
The Shell which installed in OpenWrt is ash, not bash. And ash doesn't support the arrays.
[http://lists.busybox.net/pipermail/busybox/2004-July/012110.html](http://lists.busybox.net/pipermail/busybox/2004-July/012110.html)

**Comment by goomadao** [comment]
Sorry for the late reply.
I just tested the script on my router with bash and I'm not familiar with ash.
Cause I need to update the IP v6 addresses for the router and devices connected to my router, and a single device may have multiple addresses, so it's essential to use array.
You can install bash with command `opkg update && opkg install bash` and then run this script with bash.

**Comment by cornjosh** [comment]
Oh! I forgot I can install bash by opkg. 
Thanks agian.
